name: "repo a dispara repo b"

on:
  push:
    branches: 
      - main

jobs:
  dispara:
    uses: convictional/trigger-workflow-and-wait
    with:
      owner: roselmamendestw
      repo: gh-repo-b
      github_token: ${{ secrets.gh_token }}
