name: "repo a dispara repo b"

on:
  push:
    branches: 
      - main

jobs:
  dispara:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@latest
        with:
          owner: roselmamendestw
          repo: gh-repo-b
          github_token: ${{ secrets.gh_token }}
